[package]
name = "z-biz-tool-aigen"
version = "0.2.0"
description = "AI内容制造工厂"
edition = "2021"

[lib]
name = "z_biz_tool_aigen_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = "0.2"
reqwest = { version = "0.12", features = ["json", "multipart"] }
